export const Core = [
    {
        'fullName': 'Alex Morgan',
        'username': 'Alex',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'alex.morgan@example.com',
    },
    {
        'fullName': 'Jordan Lee',
        'username': 'Jordan',
        'rollNumber': 'ED20B054',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'jordan.lee@example.com',
    },
    {
        'fullName': 'Taylor Reed',
        'username': 'Taylor',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'taylor.reed@example.com',
    },
    {
        'fullName': 'Sam Wilson',
        'username': 'Sam',
        'rollNumber': 'ED20B054',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'sam.wilson@example.com',
    },
    {
        'fullName': 'Chris Davis',
        'username': 'Chris',
        'rollNumber': 'ED20B054',
        'subModule': 'Low voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'chris.davis@example.com',
    },
    {
        'fullName': 'Pat Murphy',
        'username': 'Pat',
        'rollNumber': 'ED20B054',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'pat.murphy@example.com',
    },
    {
        'fullName': 'Morgan Smith',
        'username': 'Morgan',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'morgan.smith@example.com',
    },
]

export const Mech = [
    {
        'fullName': 'Casey Miller',
        'username': 'Casey',
        'rollNumber': 'ED20B054',
        'subModule': 'Vehicle dynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'casey.miller@example.com',
    },
    {
        'fullName': 'Riley Brown',
        'username': 'Riley',
        'rollNumber': 'ED20B054',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'riley.brown@example.com',
    },
    {
        'fullName': 'Jamie Clark',
        'username': 'Jamie',
        'rollNumber': 'ED20B054',
        'subModule': 'Vehicle dynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'jamie.clark@example.com',
    },
    {
        'fullName': 'Avery Hall',
        'username': 'Avery',
        'rollNumber': 'ED20B054',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'avery.hall@example.com',
    },
    {
        'fullName': 'Dakota White',
        'username': 'Dakota',
        'rollNumber': 'ED20B054',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'dakota.white@example.com',
    },
    {
        'fullName': 'Reese Moore',
        'username': 'Reese',
        'rollNumber': 'ED20B054',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'reese.moore@example.com',
    },
    {
        'fullName': 'Quinn Adams',
        'username': 'Quinn',
        'rollNumber': 'ED20B054',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'quinn.adams@example.com',
    },
    {
        'fullName': 'Skyler Evans',
        'username': 'Skyler',
        'rollNumber': 'ED20B054',
        'subModule': 'Aerodynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'skyler.evans@example.com',
    },
    {
        'fullName': 'Cameron Scott',
        'username': 'Cameron',
        'rollNumber': 'ED20B054',
        'subModule': 'Vehicle dynamics',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'cameron.scott@example.com',
    },
    {
        'fullName': 'Jesse Green',
        'username': 'Jesse',
        'rollNumber': 'ED20B054',
        'subModule': 'Chassis',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'jesse.green@example.com',
    },
]

export const Elec = [
    {
        'fullName': 'Drew Baker',
        'username': 'Drew',
        'rollNumber': 'ED20B054',
        'subModule': 'Low voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'drew.baker@example.com',
    },
    {
        'fullName': 'Logan Wright',
        'username': 'Logan',
        'rollNumber': 'ED20B054',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'logan.wright@example.com',
    },
    {
        'fullName': 'Parker Hill',
        'username': 'Parker',
        'rollNumber': 'ED20B054',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'parker.hill@example.com',
    },
    {
        'fullName': 'Peyton King',
        'username': 'Peyton',
        'rollNumber': 'ED20B054',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'peyton.king@example.com',
    },
    {
        'fullName': 'Hayden Allen',
        'username': 'Hayden',
        'rollNumber': 'ED20B054',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'hayden.allen@example.com',
    },
    {
        'fullName': 'Finley Young',
        'username': 'Finley',
        'rollNumber': 'ED20B054',
        'subModule': 'High voltage',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'finley.young@example.com',
    },
]

export const Spons = [
    {
        'fullName': 'Rowan Nelson',
        'username': 'Rowan',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'rowan.nelson@example.com',
    },
    {
        'fullName': 'Kendall Carter',
        'username': 'Kendall',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'kendall.carter@example.com',
    },
    {
        'fullName': 'Harper Mitchell',
        'username': 'Harper',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'harper.mitchell@example.com',
    },
    {
        'fullName': 'Emerson Perez',
        'username': 'Emerson',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'emerson.perez@example.com',
    },
    {
        'fullName': 'Sagar Nagapnor',
        'username': 'Sagar',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com/in/SagarNagapnor',
        'email': 'sagar@example.com',
    },
    {
        'fullName': 'Sydney Turner',
        'username': 'Sydney',
        'rollNumber': 'ED20B054',
        'subModule': 'NA',
        'linkedIn': 'https://www.linkedin.com',
        'email': 'sydney.turner@example.com',
    },
]